In [2]:
import numpy as np


Library used for scientific computing. 

In [5]:
#Array

my1darray = np.array([1,2,3])
print(my1darray)

my2dArray = np.array([[1,2,3],[4,5,6]])
print(my2dArray)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [10]:
my1darray.dtype
## you can select the data type 


dtype('int32')

In [9]:
my2dArray = np.array([[1,2,3],[4,5,6]], dtype = 'float32')
my2dArray.dtype

dtype('float32')

In [12]:
#can have both integers and strings
charArray = np.array([(1,"a",3), (1,2,3)])
charArray.dtype

#python parses everything as strings because python priotises unicode over integers

dtype('<U11')

In [15]:
#array initialisation 

num_rows = 2
num_columns = 3

##array of 0s, automatically a float type
array0s = np.zeros((num_rows, num_columns), dtype = "int32")
print(array0s)

array0s = np.zeros((2,3), dtype=np.int32)

[[0 0 0]
 [0 0 0]]


In [16]:
array1s = np.ones((num_rows, num_columns))
print(array1s)

array5s = 5*np.ones((num_rows, num_columns), dtype=np.int32)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
array7s = np.full((num_rows, num_columns),7)
print(array7s)
array7s.dtype
#different np routines can result in different data types so can be useful to set it yourself


[[7 7 7]
 [7 7 7]]


dtype('int32')

In [20]:
start = 10
end = 25
step = 3
#arrange is spelt arange in python
evenlystep = np.arange(start, end, step)
print(evenlystep)

[10 13 16 19 22]


In [25]:
#gen equal spaced number
number_samples = 4
evenlysample = np.linspace(start, end, number_samples, dtype = np.int32)
print(evenlysample)

[10 15 20 25]


In [27]:
identity = np.eye(3, dtype = np.int32)
print(identity)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [28]:
#will gen float numbers between 0 and 1, excludes 1
random01 = np.random.random((2,3))
print(random01)

[[0.28822022 0.00127475 0.96759802]
 [0.11560082 0.77178573 0.61687867]]


In [29]:
#specify the range of randomness before the dimensions of the matrix
randomintrange = np.random.randint(0,10,(2,3))
print(randomintrange)

[[0 9 0]
 [8 3 9]]


In [103]:
#numpy array inspection, indexing, slicing
a = np.array(([5,6,3],[2,6,1]))
a.ndim #gives dimension
a.shape #gives shape
a.size #gives size
a.dtype #gives data type
print(b)

6


In [105]:
# index row x column, indexes at zero
#if slicing rem that does not include the end range
print(a)
a[0:2,2]

[[5 6 3]
 [2 6 1]]


array([3, 1])

In [45]:
np.diag(a)


array([5, 6])

In [106]:
#check this 
np.diag(np.fliplr(a))
b = np.fliplr(a)
print(b)

[[3 6 5]
 [1 6 2]]


In [73]:
array = np.array([1,2,3,4,5,6,7,8,9])

for x in range(len(array)):
    if array[x] %2 == 1:
        array[x] *= -1

print(array)
print(len(array))

## could also write and off number function
odd_number = np.where(array %2 == 1)

array[odd_number] *= -1

[-1  2 -3  4 -5  6 -7  8 -9]
9


In [75]:
array = np.array([1,2,3,4,5,6,7,8,9])
## could also write and off number function
odd_number = np.where(array %2 == 1)

array[odd_number] *= -1
print(array)

[-1  2 -3  4 -5  6 -7  8 -9]


In [ ]:
#array arithmetics 

a1 = np.array([[1,2,3],[7,1,3]])
a2 = np.array([[4,6,9],[2,5,1]])

add1 = a1 + a2
add2 = np.add(a1,a2)

sub1 = a1 - a2
sub2 = np.subtract(a1,a2)

multi1 = a1*a2
multi2 = np.multiply(a1,a2)

div1 = a1/a2
div2 = np.divide(a1,a2)

b = np.array([4,6],[2,5],[9,1])
dotp = a.dot(b)

exp = np.exp(a)
sqroot = np.sqrt(a)
sin = np.sin(a)
cos = np.cos(a)
log = np.log(a)



In [82]:
#numpy array stats

# use axis = 0 ROW or axis = 1 COLUMN
a5 = np.array([[1,2,5],[7,1,3]])
#sum by column
sum1 = a5.sum(axis=1)
sum2 = np.sum(a5, axis=1)

print(sum1)

#max
maxi = a5.max()
maxi2 = a5.max(axis = 1)

#standard deviation

standev = np.std(a5)

#mean
avg = np.mean(a5, axis = 0)
avg = np.mean(a5)


[ 8 11]


In [ ]:
## triangle task 

a = np.array([0,0])
b = np.array([0,3])
c = np.array([1.5, 0])

from numpy import linalg as la  #norm is the euclidean distance
ab = la.norm(a-b)
ac = la.norm(a-c)
bc = la.norm(b-c)


In [111]:
a = np.array([[1,2,5],[7,1,3]])
#transpose
#aTr1 = np.transpose(a)
aTr2= a.T
print(a)
#print(aTr2)

#reshape
b = reshape = np.reshape(a,(3,2))
print(b)
reshape = a.reshape(3,2)
#reshape to row
reshapetorow= a.reshape(6) #only give a column argument, row deafults as 1

[[1 2 5]
 [7 1 3]]
[[1 2]
 [5 7]
 [1 3]]


In [116]:
# stack array

a8 = np.array([[1,2,5],[7,1,3]])
a9 = np.array([[7,8],[4,1]])
a10 = np.array([[9],[9]])

#stack horizontal, stacks on the columns 
abc = np.hstack([a8,a9,a10])
#print(abc)

#
a11 = np.array([[1,2,3],[4,5,6]])
a12 = np.array([[7,8,9],[10,11,12]])
a13 = np.array([[13,14,15],[16,17,18]])
bac = np.vstack([a11,a12,a13])
#print(bac)

#concatenate
ab = np.concatenate((a11,a12,a13),axis = 0)
ba = np.concatenate((a11,a12,a13),axis = 1)

print(ab)
print(ba)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]


In [ ]:
#save array to a file
np.save("array_a",a11) #name of file and chosen array to binary file .npy
np.savez("many_array",array1 = a11, array2 = a12) #have to store the arrays as a variable to save them .npz 

#save to text file and format preferences
# %d integer form
# %f float number
# %s string number
# %.2f float to nearest 2 dp

np.savetxt("array.txt", a11)
np.savetxt("array2.txt", a12, delimiter = ",", fmt = "%d")

#save to csv
np.savetxt("array2.csv", a12, delimiter = ",", fmt = "%d")

#load the npy file
le = np.load("array_a.npy")
print(le)

#load npz file
le2 = np.load("many_array.npz")
print(le2["array1"])
print(le2["array2"])

#load the text file
read_text = np.loadtxt("array.txt") #if has delimiter need to include it here

#load a csv file
read_text = np.loadtxt("array2.csv", delimiter = ",")



In [115]:
exportarray = np.array([[1.99,2.23],[5.30,7.75],[1.89,3.01]])
#print(exportarray)

roundedarray = np.around(exportarray, 1) #this rounds the array to 1 decimal place
stringarray = np.char.mod("%.1f", roundedarray) #this will convert to a string and also keep to 1 decimal float, so pretty much the same thing, can omit this step

row_header = np.array([["r1"],["r2"],["r3"]])
#print(row_header)

with_rowhead = np.hstack((row_header, stringarray))
#print(with_rowhead)

col_header = np.array(["-","c1","c2"])
with_colhead = np.vstack((col_header, with_rowhead))
print(with_colhead)

np.savetxt("textfile.csv", with_colhead, delimiter = ",", fmt ="%s")

[['-' 'c1' 'c2']
 ['r1' '2.0' '2.2']
 ['r2' '5.3' '7.8']
 ['r3' '1.9' '3.0']]
